# 1 Intro into torch

In [3]:
import torch
import numpy as np

Let's start with the basics. We create some dummy dataset: two observations $n$, every observation has three features $m$. We organize that as a dataset with dimensions $(n,m)$, so that is $(2,3)$

In [4]:
data = [
    [1, 2, 3],
    [10, 20, 30]
]

Our datatype here is `List[int]`, and PyTorch uses a `torch.Tensor` datatype.

In [6]:
X = torch.tensor(data)
type(X)

torch.Tensor

We can retrieve the shape

In [7]:
X.shape

torch.Size([2, 3])

And the type of the data inside the tensor:

In [8]:
X.dtype

torch.int64

Or the amount of observations:

In [9]:
len(X)

2

We can also start with a `numpy.array`

In [10]:
npdata = np.array(
    data,
    dtype = np.float32
)

Note we changed the dataformat to `np.float32`

In [11]:
X2 = torch.from_numpy(npdata)
X2

tensor([[ 1.,  2.,  3.],
        [10., 20., 30.]])

In [12]:
X2.dtype

torch.float32

We can easily create a stand in tensor, with the same shape as our data:

In [13]:
ones = torch.ones_like(X2)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Or random weights. These are uniform distributed positive numbers between 0 and 1

In [22]:
X3 = torch.rand(2,3)
X3

tensor([[0.7870, 0.5330, 0.1165],
        [0.4135, 0.8545, 0.8035]])

If we want normally distributed numbers, we need to specify mean and standard deviation:

In [32]:
X4 = torch.normal(mean=0.0, std=0.1, size=(2,3))
X4

tensor([[-0.1106,  0.0733,  0.2496],
        [-0.0683, -0.0565, -0.1663]])

If your laptop or server has a GPU, PyTorch can run the calculations on the GPU. You can check if the GPU can be found by PyTorch with:

In [33]:
torch.cuda.is_available()

False

And you can set the tensor to the GPU device with `.to()`. Default is `"cpu"`

In [34]:
if torch.cuda.is_available():
    tensor = X3.to("cuda")
else:
    print("cuda not found")
X3.device

cuda not found


device(type='cpu')

Other usefull tricks are to create an array of ones. Can you figure out how to create an array of zeros for yourself?

In [35]:
ones = torch.ones(1, 10)
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Tensors can be concatenated. We need to specify the dimension along which the concatenation is done:

In [37]:
torch.cat([ones, ones, ones], dim=0)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

The basis of most machine learning functions is the linear function. We can easily scale this by using matrix multiplication. Let's say we start with some random data, 32 observations with 10 features.

In [38]:
X = torch.rand(32, 10)

Now, if we want a linear map that transforms these 10 features into 2 dimensions, we can do that with a set of weights with dimensions $(10,2)$

In [39]:
W = torch.rand(10, 2)

In [40]:
yhat = X @ W
yhat.shape

torch.Size([32, 2])

Equivalent is this syntax:

In [41]:
yhat = torch.matmul(X, W)
yhat.shape

torch.Size([32, 2])

And finally, we can aggregate the tensor along the two features by taking the mean over the last dimension.

In [42]:
aggregate = yhat.mean(dim=1)
aggregate.shape

torch.Size([32])

Try for yourself to calculate the sum